version: '3'
services:
  mimic:
    restart: always
    image: mycroftai/mimic3
    volumes:
      - "./mimc3:/home/mimic3/.local/share/mycroft/mimic3"
  web-tts:
    build:
      context: .
      dockerfile: ./web-tts.Dockerfile
    container_name: web-tts
    ports:
      - "8000:80"
      - "4443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
